var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":240,"id":34035,"methods":[],"name":"TestContextualSerialization","sl":21},{"el":37,"id":34035,"methods":[],"name":"TestContextualSerialization.Prefix","sl":35},{"el":47,"id":34035,"methods":[{"el":43,"sc":9,"sl":43},{"el":46,"sc":9,"sl":45}],"name":"TestContextualSerialization.ContextualBean","sl":39},{"el":57,"id":34039,"methods":[{"el":56,"sc":9,"sl":56}],"name":"TestContextualSerialization.AnnotatedContextualBean","sl":50},{"el":69,"id":34041,"methods":[{"el":68,"sc":9,"sl":66}],"name":"TestContextualSerialization.ContextualBeanWrapper","sl":61},{"el":79,"id":34043,"methods":[{"el":78,"sc":9,"sl":76}],"name":"TestContextualSerialization.ContextualArrayBean","sl":71},{"el":90,"id":34045,"methods":[{"el":89,"sc":9,"sl":87}],"name":"TestContextualSerialization.ContextualArrayElementBean","sl":81},{"el":102,"id":34047,"methods":[{"el":101,"sc":9,"sl":97}],"name":"TestContextualSerialization.ContextualListBean","sl":92},{"el":108,"id":34050,"methods":[],"name":"TestContextualSerialization.ContextualMapBean","sl":104},{"el":120,"id":34050,"methods":[{"el":119,"sc":9,"sl":119}],"name":"TestContextualSerialization.BeanWithClassConfig","sl":115},{"el":159,"id":34052,"methods":[{"el":131,"sc":9,"sl":131},{"el":134,"sc":9,"sl":132},{"el":140,"sc":9,"sl":136},{"el":158,"sc":9,"sl":142}],"name":"TestContextualSerialization.AnnotatedContextualSerializer","sl":125},{"el":193,"id":34074,"methods":[{"el":168,"sc":9,"sl":168},{"el":174,"sc":9,"sl":170},{"el":180,"sc":9,"sl":176},{"el":187,"sc":9,"sl":182},{"el":192,"sc":9,"sl":189}],"name":"TestContextualSerialization.ContextualAndResolvable","sl":161}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
