var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":160,"id":34331,"methods":[{"el":135,"sc":1,"sl":127},{"el":138,"sc":1,"sl":136}],"name":"TestVisibleTypeId","sl":12},{"el":24,"id":34331,"methods":[{"el":23,"sc":9,"sl":23}],"name":"TestVisibleTypeId.PropertyBean","sl":18},{"el":36,"id":34333,"methods":[{"el":35,"sc":9,"sl":35}],"name":"TestVisibleTypeId.WrapperArrayBean","sl":30},{"el":48,"id":34335,"methods":[{"el":47,"sc":9,"sl":47}],"name":"TestVisibleTypeId.WrapperObjectBean","sl":42},{"el":55,"id":34337,"methods":[],"name":"TestVisibleTypeId.ExternalIdWrapper","sl":51},{"el":64,"id":34337,"methods":[{"el":63,"sc":9,"sl":63}],"name":"TestVisibleTypeId.ExternalIdBean","sl":58},{"el":75,"id":34339,"methods":[],"name":"TestVisibleTypeId.TypeIdFromFieldProperty","sl":70},{"el":83,"id":34339,"methods":[],"name":"TestVisibleTypeId.TypeIdFromFieldArray","sl":79},{"el":92,"id":34339,"methods":[{"el":91,"sc":9,"sl":90}],"name":"TestVisibleTypeId.TypeIdFromMethodObject","sl":87},{"el":98,"id":34341,"methods":[],"name":"TestVisibleTypeId.ExternalIdWrapper2","sl":94},{"el":108,"id":34341,"methods":[{"el":107,"sc":9,"sl":106}],"name":"TestVisibleTypeId.ExternalIdBean2","sl":100},{"el":117,"id":34343,"methods":[{"el":116,"sc":9,"sl":115}],"name":"TestVisibleTypeId.MultipleIds","sl":111}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_55":{"methods":[{"sl":136}],"name":"testTypeIdFromProperty92","pass":true,"statements":[{"sl":137}]},"test_63":{"methods":[{"sl":23},{"sl":127}],"name":"testVisibleWithProperty47","pass":true,"statements":[{"sl":23},{"sl":128},{"sl":129},{"sl":130},{"sl":131},{"sl":132},{"sl":133},{"sl":134}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [63], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [63], [63], [63], [63], [63], [63], [63], [63], [], [55], [55], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
