var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":277,"id":31065,"methods":[],"name":"TestValueAnnotations","sl":17},{"el":29,"id":31065,"methods":[],"name":"TestValueAnnotations.RootString","sl":27},{"el":40,"id":31065,"methods":[{"el":35,"sc":9,"sl":35},{"el":38,"sc":9,"sl":37},{"el":39,"sc":9,"sl":39}],"name":"TestValueAnnotations.RootStringImpl","sl":31},{"el":45,"id":31071,"methods":[],"name":"TestValueAnnotations.RootInterface","sl":43},{"el":54,"id":31071,"methods":[{"el":50,"sc":9,"sl":50},{"el":53,"sc":9,"sl":52}],"name":"TestValueAnnotations.RootInterfaceImpl","sl":47},{"el":58,"id":31074,"methods":[],"name":"TestValueAnnotations.RootMap","sl":58},{"el":62,"id":31074,"methods":[],"name":"TestValueAnnotations.RootList","sl":62},{"el":79,"id":31074,"methods":[{"el":68,"sc":9,"sl":68},{"el":78,"sc":9,"sl":70}],"name":"TestValueAnnotations.RootStringDeserializer","sl":65},{"el":102,"id":31082,"methods":[{"el":101,"sc":9,"sl":97}],"name":"TestValueAnnotations.CollectionHolder","sl":90},{"el":120,"id":31084,"methods":[{"el":119,"sc":9,"sl":115}],"name":"TestValueAnnotations.MapHolder","sl":107},{"el":135,"id":31086,"methods":[{"el":134,"sc":9,"sl":129}],"name":"TestValueAnnotations.ArrayHolder","sl":125},{"el":144,"id":31088,"methods":[{"el":143,"sc":9,"sl":142}],"name":"TestValueAnnotations.BrokenCollectionHolder","sl":140},{"el":157,"id":31089,"methods":[{"el":156,"sc":9,"sl":156}],"name":"TestValueAnnotations.StringWrapper","sl":152},{"el":169,"id":31091,"methods":[{"el":168,"sc":9,"sl":163}],"name":"TestValueAnnotations.MapKeyHolder","sl":159},{"el":176,"id":31093,"methods":[{"el":175,"sc":9,"sl":174}],"name":"TestValueAnnotations.BrokenMapKeyHolder","sl":171},{"el":192,"id":31094,"methods":[{"el":191,"sc":9,"sl":188}],"name":"TestValueAnnotations.ListContentHolder","sl":184},{"el":204,"id":31096,"methods":[{"el":203,"sc":9,"sl":202}],"name":"TestValueAnnotations.InvalidContentClass","sl":194},{"el":215,"id":31097,"methods":[{"el":214,"sc":9,"sl":210}],"name":"TestValueAnnotations.ArrayContentHolder","sl":206},{"el":226,"id":31099,"methods":[{"el":225,"sc":9,"sl":221}],"name":"TestValueAnnotations.MapContentHolder","sl":217}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
