var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":69,"id":2252,"methods":[{"el":15,"sc":1,"sl":14},{"el":17,"sc":1,"sl":16},{"el":19,"sc":1,"sl":18},{"el":21,"sc":1,"sl":20},{"el":23,"sc":1,"sl":22},{"el":25,"sc":1,"sl":24},{"el":27,"sc":1,"sl":26},{"el":29,"sc":1,"sl":28},{"el":31,"sc":1,"sl":30},{"el":33,"sc":1,"sl":32},{"el":35,"sc":1,"sl":34},{"el":37,"sc":1,"sl":36},{"el":39,"sc":1,"sl":38},{"el":41,"sc":1,"sl":40}],"name":"ElementsTest","sl":13}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":26}],"name":"hasText3","pass":false,"statements":[{"sl":27}]},"test_11":{"methods":[{"sl":34}],"name":"is2","pass":false,"statements":[{"sl":35}]},"test_16":{"methods":[{"sl":22}],"name":"hasText5","pass":false,"statements":[{"sl":23}]},"test_20":{"methods":[{"sl":40}],"name":"collect","pass":true,"statements":[{"sl":41}]},"test_27":{"methods":[{"sl":20}],"name":"val1","pass":false,"statements":[{"sl":21}]},"test_3":{"methods":[{"sl":36}],"name":"is1","pass":false,"statements":[{"sl":37}]},"test_60":{"methods":[{"sl":32}],"name":"is","pass":true,"statements":[{"sl":33}]},"test_63":{"methods":[{"sl":24}],"name":"hasText4","pass":false,"statements":[{"sl":25}]},"test_68":{"methods":[{"sl":16}],"name":"val3","pass":false,"statements":[{"sl":17}]},"test_69":{"methods":[{"sl":38}],"name":"testGetElementsByAttributeValue112","pass":false,"statements":[{"sl":39}]},"test_78":{"methods":[{"sl":18}],"name":"val2","pass":false,"statements":[{"sl":19}]},"test_79":{"methods":[{"sl":28}],"name":"select2","pass":false,"statements":[{"sl":29}]},"test_80":{"methods":[{"sl":30}],"name":"select1","pass":false,"statements":[{"sl":31}]},"test_82":{"methods":[{"sl":14}],"name":"val","pass":false,"statements":[{"sl":15}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [82], [82], [68], [68], [78], [78], [27], [27], [16], [16], [63], [63], [1], [1], [79], [79], [80], [80], [60], [60], [11], [11], [3], [3], [69], [69], [20], [20], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
