var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":27,"id":12988,"methods":[{"el":21,"sc":5,"sl":18},{"el":26,"sc":5,"sl":23}],"name":"JsonParseException","sl":13}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_107":{"methods":[{"sl":18}],"name":"testUnclosedArray18","pass":true,"statements":[{"sl":20}]},"test_114":{"methods":[{"sl":18}],"name":"testSingleQuotesDefault65","pass":true,"statements":[{"sl":20}]},"test_17":{"methods":[{"sl":18}],"name":"testCommentsDisabled73","pass":true,"statements":[{"sl":20}]},"test_18":{"methods":[{"sl":18}],"name":"testAllowNaN20","pass":true,"statements":[{"sl":20}]},"test_26":{"methods":[{"sl":18}],"name":"testMisssingColon55","pass":true,"statements":[{"sl":20}]},"test_31":{"methods":[{"sl":18}],"name":"testTabsDefault88","pass":true,"statements":[{"sl":20}]},"test_40":{"methods":[{"sl":18}],"name":"testInvalidExtraComma57","pass":true,"statements":[{"sl":20}]},"test_41":{"methods":[{"sl":18}],"name":"testLeadingZeroesReader21","pass":true,"statements":[{"sl":20}]},"test_47":{"methods":[{"sl":18}],"name":"testLeadingZeroesUTF847","pass":true,"statements":[{"sl":20}]},"test_49":{"methods":[{"sl":18}],"name":"testWeirdToken59","pass":true,"statements":[{"sl":20}]},"test_52":{"methods":[{"sl":18}],"name":"testLongOverflow28","pass":true,"statements":[{"sl":20}]},"test_61":{"methods":[{"sl":18}],"name":"testQuotesRequired114","pass":true,"statements":[{"sl":20}]},"test_62":{"methods":[{"sl":18}],"name":"testInvalidBooleanAccess85","pass":true,"statements":[{"sl":20}]},"test_66":{"methods":[{"sl":18}],"name":"testSimpleLong22","pass":true,"statements":[{"sl":20}]},"test_80":{"methods":[{"sl":18}],"name":"testEOFInName64","pass":true,"statements":[{"sl":20}]},"test_81":{"methods":[{"sl":18}],"name":"testInvalidIntAccess13","pass":true,"statements":[{"sl":20}]},"test_85":{"methods":[{"sl":18}],"name":"testMismatchObjectToArray54","pass":true,"statements":[{"sl":20}]},"test_89":{"methods":[{"sl":18}],"name":"testInvalidKeywordsStream70","pass":true,"statements":[{"sl":20}]},"test_91":{"methods":[{"sl":18}],"name":"testInvalidMissingFieldName69","pass":true,"statements":[{"sl":20}]},"test_96":{"methods":[{"sl":18}],"name":"testNumbers27","pass":true,"statements":[{"sl":20}]},"test_99":{"methods":[{"sl":18}],"name":"testInvalidKeywordsReader1","pass":true,"statements":[{"sl":20}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [31, 89, 85, 66, 91, 17, 49, 99, 62, 61, 96, 52, 107, 26, 47, 80, 114, 18, 81, 41, 40], [], [31, 89, 85, 66, 91, 17, 49, 99, 62, 61, 96, 52, 107, 26, 47, 80, 114, 18, 81, 41, 40], [], [], [], [], [], [], []]
