var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":130,"id":31056,"methods":[{"el":104,"sc":1,"sl":96},{"el":114,"sc":1,"sl":107}],"name":"TestFieldDeserialization","sl":14},{"el":32,"id":31056,"methods":[],"name":"TestFieldDeserialization.SimpleFieldBean","sl":23},{"el":37,"id":31056,"methods":[],"name":"TestFieldDeserialization.SimpleFieldBean2","sl":34},{"el":47,"id":31056,"methods":[],"name":"TestFieldDeserialization.NoAutoDetectBean","sl":40},{"el":56,"id":31056,"methods":[],"name":"TestFieldDeserialization.DupFieldBean","sl":50},{"el":65,"id":31056,"methods":[],"name":"TestFieldDeserialization.DupFieldBean2","sl":58},{"el":74,"id":31056,"methods":[],"name":"TestFieldDeserialization.OkDupFieldBean","sl":67},{"el":76,"id":31056,"methods":[],"name":"TestFieldDeserialization.Abstract","sl":76},{"el":82,"id":31056,"methods":[{"el":81,"sc":9,"sl":81}],"name":"TestFieldDeserialization.Concrete","sl":77},{"el":87,"id":31058,"methods":[],"name":"TestFieldDeserialization.AbstractWrapper","sl":84}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_312":{"methods":[{"sl":81},{"sl":107}],"name":"testTypeAnnotation358","pass":true,"statements":[{"sl":81},{"sl":108},{"sl":109},{"sl":110},{"sl":111},{"sl":112},{"sl":113}]},"test_492":{"methods":[{"sl":96}],"name":"testSimpleAnnotation21","pass":true,"statements":[{"sl":97},{"sl":98},{"sl":99},{"sl":100},{"sl":101},{"sl":102},{"sl":103}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [312], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [492], [492], [492], [492], [492], [492], [492], [492], [], [], [], [312], [312], [312], [312], [312], [312], [312], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
