var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":258,"id":23867,"methods":[{"el":66,"sc":5,"sl":64},{"el":79,"sc":5,"sl":68},{"el":141,"sc":5,"sl":81},{"el":224,"sc":5,"sl":143},{"el":256,"sc":5,"sl":236}],"name":"ZoomHandler","sl":55}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_109":{"methods":[{"sl":64}],"name":"test2502355_restoreAutoBounds395","pass":true,"statements":[{"sl":65}]},"test_1281":{"methods":[{"sl":64}],"name":"test2502355_zoomInBoth393","pass":true,"statements":[{"sl":65}]},"test_1334":{"methods":[{"sl":64}],"name":"testConstructor154","pass":true,"statements":[{"sl":65}]},"test_214":{"methods":[{"sl":64}],"name":"testSetChart392","pass":true,"statements":[{"sl":65}]},"test_281":{"methods":[{"sl":64}],"name":"test2502355_zoomInRange233","pass":true,"statements":[{"sl":65}]},"test_318":{"methods":[{"sl":64}],"name":"test2502355_zoomInRange233","pass":true,"statements":[{"sl":65}]},"test_696":{"methods":[{"sl":64}],"name":"test2502355_zoomOutRange394","pass":true,"statements":[{"sl":65}]},"test_733":{"methods":[{"sl":64}],"name":"test2502355_zoomInBoth393","pass":true,"statements":[{"sl":65}]},"test_93":{"methods":[{"sl":64}],"name":"test2502355_restoreAutoBounds395","pass":true,"statements":[{"sl":65}]},"test_97":{"methods":[{"sl":64}],"name":"test2502355_zoomOutRange394","pass":true,"statements":[{"sl":65}]},"test_984":{"methods":[{"sl":64}],"name":"testConstructor154","pass":true,"statements":[{"sl":65}]},"test_99":{"methods":[{"sl":64}],"name":"testSetChart392","pass":true,"statements":[{"sl":65}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [97, 1281, 696, 99, 214, 281, 1334, 93, 984, 733, 109, 318], [97, 1281, 696, 99, 214, 281, 1334, 93, 984, 733, 109, 318], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
