var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":238,"id":32976,"methods":[{"el":163,"sc":1,"sl":147}],"name":"TestArrayDeserialization","sl":20},{"el":61,"id":32976,"methods":[{"el":36,"sc":9,"sl":35},{"el":43,"sc":9,"sl":38},{"el":45,"sc":9,"sl":45},{"el":46,"sc":9,"sl":46},{"el":47,"sc":9,"sl":47},{"el":49,"sc":9,"sl":49},{"el":50,"sc":9,"sl":50},{"el":51,"sc":9,"sl":51},{"el":60,"sc":9,"sl":53}],"name":"TestArrayDeserialization.Bean1","sl":29},{"el":98,"id":33000,"methods":[{"el":76,"sc":9,"sl":73},{"el":83,"sc":9,"sl":78},{"el":85,"sc":9,"sl":85},{"el":91,"sc":9,"sl":87},{"el":97,"sc":9,"sl":93}],"name":"TestArrayDeserialization.Bean2","sl":68},{"el":102,"id":33014,"methods":[],"name":"TestArrayDeserialization.ObjectWrapper","sl":100},{"el":106,"id":33014,"methods":[],"name":"TestArrayDeserialization.ObjectArrayWrapper","sl":104},{"el":119,"id":33014,"methods":[{"el":118,"sc":9,"sl":110}],"name":"TestArrayDeserialization.CustomNonDeserArrayDeserializer","sl":108},{"el":127,"id":33021,"methods":[{"el":126,"sc":9,"sl":124}],"name":"TestArrayDeserialization.NonDeserializable","sl":121},{"el":132,"id":33023,"methods":[],"name":"TestArrayDeserialization.Product","sl":129},{"el":137,"id":33023,"methods":[],"name":"TestArrayDeserialization.Things","sl":134}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_60":{"methods":[{"sl":147}],"name":"testNonRootArraysUsingParser166","pass":true,"statements":[{"sl":148},{"sl":149},{"sl":150},{"sl":151},{"sl":152},{"sl":153},{"sl":154},{"sl":155},{"sl":156},{"sl":157},{"sl":158},{"sl":159},{"sl":160},{"sl":161},{"sl":162}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [60], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
