var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":161,"id":34129,"methods":[{"el":110,"sc":1,"sl":105},{"el":118,"sc":1,"sl":113},{"el":123,"sc":1,"sl":121}],"name":"TestPOJOAsArray","sl":13},{"el":24,"id":34129,"methods":[{"el":20,"sc":9,"sl":20},{"el":23,"sc":9,"sl":21}],"name":"TestPOJOAsArray.Pojo","sl":15},{"el":41,"id":34132,"methods":[{"el":34,"sc":9,"sl":34},{"el":40,"sc":9,"sl":35}],"name":"TestPOJOAsArray.PojoValue","sl":28},{"el":58,"id":34138,"methods":[{"el":51,"sc":9,"sl":51},{"el":57,"sc":9,"sl":52}],"name":"TestPOJOAsArray.FlatPojo","sl":45},{"el":68,"id":34144,"methods":[{"el":67,"sc":9,"sl":64}],"name":"TestPOJOAsArray.ForceArraysIntrospector","sl":60},{"el":72,"id":34146,"methods":[],"name":"TestPOJOAsArray.A","sl":70},{"el":78,"id":34146,"methods":[],"name":"TestPOJOAsArray.B","sl":75},{"el":84,"id":34146,"methods":[],"name":"TestPOJOAsArray.SingleBean","sl":82},{"el":91,"id":34146,"methods":[],"name":"TestPOJOAsArray.TwoStringsBean","sl":88}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_100":{"methods":[{"sl":64},{"sl":113}],"name":"testAnnotationOverride337","pass":true,"statements":[{"sl":66},{"sl":114},{"sl":115},{"sl":116},{"sl":117}]},"test_22":{"methods":[{"sl":105}],"name":"testSerializeAsArrayWithSingleProperty36","pass":true,"statements":[{"sl":106},{"sl":107},{"sl":108},{"sl":109}]},"test_40":{"methods":[{"sl":121}],"name":"testNullColumn576","pass":true,"statements":[{"sl":122}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [100], [], [100], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [22], [22], [22], [22], [22], [], [], [], [100], [100], [100], [100], [100], [], [], [], [40], [40], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
