var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":201,"id":33335,"methods":[{"el":135,"sc":5,"sl":128}],"name":"TestTypeFactory","sl":21},{"el":30,"id":33335,"methods":[],"name":"TestTypeFactory.EnumForCanonical","sl":30},{"el":32,"id":33335,"methods":[],"name":"TestTypeFactory.SingleArgGeneric","sl":32},{"el":34,"id":33335,"methods":[],"name":"TestTypeFactory.MyMap","sl":34},{"el":35,"id":33335,"methods":[],"name":"TestTypeFactory.IntermediateMap","sl":35},{"el":37,"id":33335,"methods":[],"name":"TestTypeFactory.MyList","sl":37},{"el":38,"id":33335,"methods":[],"name":"TestTypeFactory.IntermediateList","sl":38},{"el":41,"id":33335,"methods":[],"name":"TestTypeFactory.GenericList","sl":41},{"el":43,"id":33335,"methods":[],"name":"TestTypeFactory.MapInterface","sl":43},{"el":44,"id":33335,"methods":[],"name":"TestTypeFactory.IntermediateInterfaceMap","sl":44},{"el":47,"id":33335,"methods":[],"name":"TestTypeFactory.MyStringIntMap","sl":47},{"el":49,"id":33335,"methods":[],"name":"TestTypeFactory.MyStringXMap","sl":49},{"el":52,"id":33335,"methods":[],"name":"TestTypeFactory.IntLongMap","sl":52},{"el":54,"id":33335,"methods":[],"name":"TestTypeFactory.XLongMap","sl":54},{"el":55,"id":33335,"methods":[],"name":"TestTypeFactory.XXMap","sl":55},{"el":60,"id":33335,"methods":[],"name":"TestTypeFactory.SneakyBean","sl":57},{"el":65,"id":33335,"methods":[{"el":64,"sc":9,"sl":64}],"name":"TestTypeFactory.SneakyBean2","sl":62},{"el":68,"id":33337,"methods":[],"name":"TestTypeFactory.LongValuedMap","sl":68},{"el":72,"id":33337,"methods":[],"name":"TestTypeFactory.StringLongMapBean","sl":70},{"el":76,"id":33337,"methods":[],"name":"TestTypeFactory.StringListBean","sl":74}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
